name: Run Tests

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ dev ]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        # Remove cache dependency path to avoid issues
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Tests
      run: npm test -- --watchAll=false
      
    - name: Run Test Coverage
      run: npm run test:coverage
      
  backend-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fix API Endpoint Paths in Tests
      run: |
        echo "Original test file content:"
        grep -n "/api/" app/tests/test_api_endpoints.py || echo "No '/api/' endpoints found"
        
        # Fix the API endpoint paths
        sed -i 's|client.post("/api/"|client.post("/api/analytics/"|g' app/tests/test_api_endpoints.py
        sed -i 's|client.get("/api/"|client.get("/api/analytics/"|g' app/tests/test_api_endpoints.py
        sed -i 's|client.get("/api/current"|client.get("/api/analytics/current"|g' app/tests/test_api_endpoints.py
        sed -i 's|client.get("/api/url/|client.get("/api/analytics/url/|g' app/tests/test_api_endpoints.py
        sed -i 's|client.get("/api/history"|client.get("/api/analytics/history"|g' app/tests/test_api_endpoints.py
        
        echo "Modified test file content:"
        grep -n "/api/" app/tests/test_api_endpoints.py
        
    - name: Run Tests with Verbose Output
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest -v
