name: Run Tests

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ dev ]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Run Tests
      run: npm test -- --watchAll=false
      
    - name: Run Test Coverage
      run: npm run test:coverage
      
  backend-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: './backend/requirements.txt'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest
